# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'listTemplateWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQtGuiLib.header import (
    QWidget,
    QHBoxLayout,
    QVBoxLayout,
    QListWidget,
    QSize,
    QStackedWidget
)


class ListTemplateWindowUI(QWidget):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.setWindowTitle("ListTemplateWindow")
        self.setupUi()

    def setupUi(self):
        self.resize(1229, 746)
        self.horizontalLayout = QHBoxLayout(self)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_widget = QWidget(self)
        self.left_widget.setMaximumSize(QSize(260, 16777215))
        self.left_widget.setStyleSheet("border: 1px solid rgb(170, 170, 127);")
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout = QVBoxLayout(self.left_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_widget = QWidget(self.left_widget)
        self.title_widget.setMinimumSize(QSize(0, 100))
        self.title_widget.setMaximumSize(QSize(16777215, 100))
        self.title_widget.setStyleSheet("border: 1px solid rgb(0, 85, 255);")
        self.title_widget.setObjectName("title_widget")
        self.verticalLayout.addWidget(self.title_widget)
        self.listWidget = QListWidget(self.left_widget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout.addWidget(self.left_widget)
        self.body_widget = QWidget(self)
        self.body_widget.setStyleSheet("border: 1px solid rgb(0, 170, 255);")
        self.body_widget.setObjectName("body_widget")
        self.verticalLayout_2 = QVBoxLayout(self.body_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.head_widget = QWidget(self.body_widget)
        self.head_widget.setMinimumSize(QSize(0, 100))
        self.head_widget.setMaximumSize(QSize(16777215, 100))
        self.head_widget.setStyleSheet("border:1px solid rgb(85, 85, 0);")
        self.head_widget.setObjectName("head_widget")
        self.horizontalLayout_2 = QHBoxLayout(self.head_widget)
        self.horizontalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.head_left_widget = QWidget(self.head_widget)
        self.head_left_widget.setMinimumSize(QSize(90, 0))
        self.head_left_widget.setMaximumSize(QSize(90, 16777215))
        self.head_left_widget.setObjectName("head_left_widget")
        self.horizontalLayout_2.addWidget(self.head_left_widget)
        self.head_middle_widget = QWidget(self.head_widget)
        self.head_middle_widget.setObjectName("head_middle_widget")
        self.horizontalLayout_2.addWidget(self.head_middle_widget)
        self.head_right_widget = QWidget(self.head_widget)
        self.head_right_widget.setMinimumSize(QSize(141, 0))
        self.head_right_widget.setMaximumSize(QSize(90, 16777215))
        self.head_right_widget.setObjectName("head_right_widget")
        self.horizontalLayout_2.addWidget(self.head_right_widget)
        self.verticalLayout_2.addWidget(self.head_widget)
        self.stackedWidget = QStackedWidget(self.body_widget)
        self.stackedWidget.setStyleSheet("border:1px solid rgb(255, 170, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.body_widget)

